# Generated by Django 4.0.3 on 2022-03-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_countries_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(help_text='Unique id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('menu', models.CharField(blank=True, max_length=50)),
                ('country', models.ManyToManyField(blank=True, related_name='system_module_countries', to='users.countries')),
            ],
            options={
                'verbose_name_plural': 'System Module',
            },
        ),
    ]
