# Generated by Django 4.0.3 on 2022-04-01 20:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(help_text='Unique id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('countries', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Advertiser_Countries', to='users.countries')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'System Advertiser',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(help_text='Unique id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('menu', models.CharField(blank=True, max_length=50)),
                ('country', models.ManyToManyField(blank=True, related_name='system_module_countries', to='users.countries')),
            ],
            options={
                'verbose_name_plural': 'System Module',
            },
        ),
        migrations.CreateModel(
            name='ConfigruationAdvertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('name_configuration', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_time_update', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('configuration', models.TextField()),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ConfigurationAdvertiser_Advertiser', to='system.advertiser')),
            ],
            options={
                'verbose_name_plural': 'System Configuration Advertiser',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Channel_Advertiser', to='system.advertiser')),
            ],
            options={
                'verbose_name_plural': 'System Channel',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('campaign_name', models.CharField(blank=True, max_length=100)),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Campaign_Advertiser', to='system.advertiser')),
                ('module', models.ManyToManyField(blank=True, related_name='Campaign_Advertiser_module', to='system.module')),
            ],
            options={
                'verbose_name_plural': 'System Campaign',
            },
        ),
    ]
