# Generated by Django 4.0.3 on 2022-03-30 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_countries_alter_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(help_text='Unique id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('countries', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Advertiser_Countries', to='users.countries')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'System Advertiser',
            },
        ),
    ]
