# Generated by Django 4.0.3 on 2022-03-30 16:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_advertiser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigruationAdvertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('name_configuration', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_time_update', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('configuration', models.TextField()),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ConfigurationAdvertiser_Advertiser', to='system.advertiser')),
            ],
            options={
                'verbose_name_plural': 'System Configuration Advertiser',
            },
        ),
    ]
