# Generated by Django 4.0.3 on 2022-03-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_configruationadvertiser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Channel_Advertiser', to='system.advertiser')),
            ],
            options={
                'verbose_name_plural': 'System Channel',
            },
        ),
    ]
