# Generated by Django 4.0.3 on 2022-03-30 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('campaign_name', models.CharField(blank=True, max_length=100)),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Campaign_Advertiser', to='system.advertiser')),
                ('module', models.ManyToManyField(blank=True, related_name='Campaign_Advertiser_module', to='system.module')),
            ],
            options={
                'verbose_name_plural': 'Campaign',
            },
        ),
    ]
