# Generated by Django 4.0.3 on 2022-04-01 20:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ConversionGroup_Advertiser', to='system.advertiser')),
            ],
            options={
                'verbose_name_plural': 'MTA ConversionGroup',
            },
        ),
        migrations.CreateModel(
            name='ConversionType',
            fields=[
                ('id', models.AutoField(help_text='Unique id', primary_key=True, serialize=False)),
                ('conversion_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ConversionType_Advertiser', to='system.advertiser')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ConversionType_Campaign', to='system.campaign')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mta.conversiongroup')),
            ],
            options={
                'verbose_name_plural': 'MTA ConversionType',
            },
        ),
        migrations.CreateModel(
            name='TargetGroupConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=200)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.advertiser')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mta.conversiongroup')),
            ],
            options={
                'verbose_name_plural': 'MTA Target Group Conversion',
            },
        ),
        migrations.CreateModel(
            name='PathsMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Date')),
                ('total_paths', models.FloatField(blank=True, default=0, help_text='total_paths')),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MTAPathsMetrics_Advertiser', to='system.advertiser')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MTAPathsMetrics_Campaign', to='system.campaign')),
            ],
            options={
                'verbose_name_plural': 'MTA Paths Metrics',
            },
        ),
        migrations.CreateModel(
            name='PathAnalisisTouchpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Date')),
                ('touchpoints_quantity', models.FloatField(blank=True, default=0, help_text='total_paths')),
                ('paths_count', models.FloatField(blank=True, default=0, help_text='total_paths')),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MTAPathAnalisisTouchpoint_Advertiser', to='system.advertiser')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MTAPathAnalisisTouchpoint_Campaign', to='system.campaign')),
                ('conversion_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MtaPathAnalisisTouchpoint_conversionType', to='mta.conversiontype')),
            ],
            options={
                'verbose_name_plural': 'MTA Path Analisis Touchpoint',
            },
        ),
        migrations.CreateModel(
            name='PathAnalisisChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Date')),
                ('channels_quantity', models.FloatField(blank=True, default=0, help_text='total_paths')),
                ('paths_count', models.FloatField(blank=True, default=0, help_text='total_paths')),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MTAPathAnalisisChannels_Advertiser', to='system.advertiser')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MTAPathAnalisisChannels_Campaign', to='system.campaign')),
                ('conversion_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MtaPathAnalisisChannels_conversionType', to='mta.conversiontype')),
            ],
            options={
                'verbose_name_plural': 'MTA Path Analisis Channels',
            },
        ),
        migrations.CreateModel(
            name='MtaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, help_text='Date')),
                ('revenue_shapley', models.FloatField(blank=True, default=0, help_text='Revenue shapley')),
                ('atributed_conversion_shapley', models.FloatField(blank=True, default=0, help_text='Atributed Conversion Shapley')),
                ('atributed_conversiones_lineal', models.FloatField(blank=True, default=0, help_text='Atributed Conversiones Lineal')),
                ('revenue_linear', models.FloatField(blank=True, default=0, help_text='Revenue Linear')),
                ('revenue_first_click', models.FloatField(blank=True, default=0, help_text='Revenue_Frst Click')),
                ('revenue_last_click', models.FloatField(blank=True, default=0, help_text='Revenue Last Click')),
                ('stimuli_quantity_paths', models.FloatField(blank=True, default=0, help_text='Stimuli Quantity Paths')),
                ('paths_quantity', models.FloatField(blank=True, default=0, help_text='Paths Quantity')),
                ('assistances_role', models.FloatField(blank=True, default=0, help_text='Rol assistances (of the paths ending today)')),
                ('conversion_role', models.FloatField(blank=True, default=0, help_text='Role conversion (of the paths ending today)')),
                ('acquisition_role', models.FloatField(blank=True, default=0, help_text='Acquisition role(of the paths ending today)')),
                ('shapley', models.FloatField(blank=True, default=0, help_text='Shapley')),
                ('this_type_conversions', models.FloatField(blank=True, default=0, help_text='This type conversions')),
                ('convertion_paths_with_this_channel', models.FloatField(blank=True, default=0, help_text='Convertion paths with this channel')),
                ('daily_impulses', models.FloatField(blank=True, default=0, help_text='Daily impulses')),
                ('campaign_mta', models.CharField(db_index=True, default='', max_length=300)),
                ('source', models.CharField(db_index=True, default='', max_length=100)),
                ('content', models.CharField(db_index=True, default='', max_length=300)),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MtaResult_Advertiser', to='system.advertiser')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MtaResult_Campaign', to='system.campaign')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MtaResult_chanel', to='system.channel')),
                ('conversion_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MtaResult_conversionType', to='mta.conversiontype')),
            ],
            options={
                'verbose_name_plural': 'MTA Result',
            },
        ),
        migrations.CreateModel(
            name='Irma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Date')),
                ('len_coalitions', models.IntegerField(default=0, help_text='Len coalitions')),
                ('coalitions', models.FloatField(blank=True, default=0, help_text='coalitions')),
                ('conversion_volume', models.FloatField(blank=True, default=0, help_text='conversion_volume')),
                ('conversion_percentage', models.FloatField(blank=True, default=0, help_text='conversion_percentage')),
                ('possible_truncation', models.FloatField(blank=True, default=0, help_text='Possible truncation')),
                ('zero_percentage', models.FloatField(default=0, help_text='zero_percentage')),
                ('zero_ten_percentage', models.FloatField(default=0, help_text='zero_ten_percentage')),
                ('ten_twenty_percentage', models.FloatField(default=0, help_text='ten_twenty_percentage')),
                ('twenty_thirty_percentage', models.FloatField(default=0, help_text='twenty_thirty_percentage')),
                ('thirty_fourty_percentage', models.FloatField(default=0, help_text='thirty_fourty_percentage')),
                ('fourty_fifty_percentage', models.FloatField(default=0, help_text='fourty_fifty_percentage')),
                ('fifty_sixty_percentage', models.FloatField(default=0, help_text='fifty_sixty_percentage')),
                ('sixty_seventy_percentage', models.FloatField(default=0, help_text='sixty_seventy_percentage')),
                ('seventy_eighty_percentage', models.FloatField(default=0, help_text='seventy_eighty_percentage')),
                ('eighty_ninety_percentage', models.FloatField(default=0, help_text='eighty_ninety_percentage')),
                ('ninety_onehundred_percentage', models.FloatField(default=0, help_text='ninety_onehundred_percentage')),
                ('one_hundred_percentage', models.FloatField(default=0, help_text='one_hundred_percentage')),
                ('total', models.FloatField(default=0, help_text='total')),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MTAIrma_Advertiser', to='system.advertiser')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MTAIrma_Campaign', to='system.campaign')),
            ],
            options={
                'verbose_name_plural': 'MTA Irma',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('invesment', models.FloatField(blank=True, default=0, help_text='invesment')),
                ('campaign_mta', models.CharField(default='', max_length=300)),
                ('source', models.CharField(default='', max_length=100)),
                ('content', models.CharField(default='', max_length=300)),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MtaInvesment_Advertiser', to='system.advertiser')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MTAInvesment_Campaign', to='system.campaign')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MTAInvesment_chanel', to='system.channel')),
            ],
            options={
                'verbose_name_plural': 'MTA Invesment',
            },
        ),
        migrations.CreateModel(
            name='CoalitionsMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Date')),
                ('coalitions', models.CharField(max_length=200)),
                ('len_coalitions', models.IntegerField(default=0, help_text='Len Coalitions')),
                ('total_paths', models.FloatField(blank=True, default=0, help_text='total')),
                ('conversion_paths', models.FloatField(blank=True, default=0, help_text='conversion_paths')),
                ('conversion_rate', models.FloatField(blank=True, default=0, help_text='conversion_rate')),
                ('channel_attribution', models.FloatField(blank=True, default=0, help_text='channel_attribution')),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MTACoalitionsMetrics_Advertiser', to='system.advertiser')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MTACoalitionsMetrics_Campaign', to='system.campaign')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MTACoalitionsMetrics_chanel', to='system.channel')),
            ],
            options={
                'verbose_name_plural': 'MTA CoalitionsMetrics',
            },
        ),
        migrations.CreateModel(
            name='CampaingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('value', models.CharField(blank=True, max_length=50)),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CampaingType_advertiser', to='system.advertiser')),
            ],
            options={
                'verbose_name_plural': 'MTA Campaign Type',
            },
        ),
        migrations.CreateModel(
            name='CampaingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('value', models.CharField(blank=True, max_length=50)),
                ('sub', models.BooleanField(default=False)),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CampaingCategory_advertiser', to='system.advertiser')),
            ],
            options={
                'verbose_name_plural': 'MTA Campaign Category',
            },
        ),
    ]
