# Generated by Django 4.0.3 on 2022-03-30 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0005_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ConversionGroup_Advertiser', to='system.advertiser')),
            ],
            options={
                'verbose_name_plural': 'MTA ConversionGroup',
            },
        ),
        migrations.CreateModel(
            name='ConversionType',
            fields=[
                ('id', models.AutoField(help_text='Unique id', primary_key=True, serialize=False)),
                ('conversion_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ConversionType_Advertiser', to='system.advertiser')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ConversionType_Campaign', to='system.campaign')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mta.conversiongroup')),
            ],
            options={
                'verbose_name_plural': 'MTA ConversionType',
            },
        ),
    ]
