# Generated by Django 4.0.3 on 2022-03-30 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_campaign'),
        ('mta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetGroupConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=200)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.advertiser')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mta.conversiongroup')),
            ],
            options={
                'verbose_name_plural': 'MTA Target Group Conversion',
            },
        ),
    ]
