# Generated by Django 4.0.3 on 2022-03-30 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_campaign'),
        ('mta', '0002_targetgroupconversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathsMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Date')),
                ('total_paths', models.FloatField(blank=True, default=0, help_text='total_paths')),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MTAPathsMetrics_Advertiser', to='system.advertiser')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MTAPathsMetrics_Campaign', to='system.campaign')),
            ],
            options={
                'verbose_name_plural': 'MTA Paths Metrics',
            },
        ),
        migrations.CreateModel(
            name='MtaResult',
            fields=[
                ('id', models.AutoField(help_text='Unique id', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_index=True, help_text='Date')),
                ('revenue_shapley', models.FloatField(blank=True, default=0, help_text='Revenue shapley')),
                ('atributed_conversion_shapley', models.FloatField(blank=True, default=0, help_text='Atributed Conversion Shapley')),
                ('atributed_conversiones_lineal', models.FloatField(blank=True, default=0, help_text='Atributed Conversiones Lineal')),
                ('revenue_linear', models.FloatField(blank=True, default=0, help_text='Revenue Linear')),
                ('revenue_first_click', models.FloatField(blank=True, default=0, help_text='Revenue_Frst Click')),
                ('revenue_last_click', models.FloatField(blank=True, default=0, help_text='Revenue Last Click')),
                ('stimuli_quantity_paths', models.FloatField(blank=True, default=0, help_text='Stimuli Quantity Paths')),
                ('paths_quantity', models.FloatField(blank=True, default=0, help_text='Paths Quantity')),
                ('assistances_role', models.FloatField(blank=True, default=0, help_text='Rol assistances (of the paths ending today)')),
                ('conversion_role', models.FloatField(blank=True, default=0, help_text='Role conversion (of the paths ending today)')),
                ('acquisition_role', models.FloatField(blank=True, default=0, help_text='Acquisition role(of the paths ending today)')),
                ('shapley', models.FloatField(blank=True, default=0, help_text='Shapley')),
                ('this_type_conversions', models.FloatField(blank=True, default=0, help_text='This type conversions')),
                ('convertion_paths_with_this_channel', models.FloatField(blank=True, default=0, help_text='Convertion paths with this channel')),
                ('daily_impulses', models.FloatField(blank=True, default=0, help_text='Daily impulses')),
                ('campaign_mta', models.CharField(db_index=True, default='', max_length=300)),
                ('source', models.CharField(db_index=True, default='', max_length=100)),
                ('content', models.CharField(db_index=True, default='', max_length=300)),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MtaResult_Advertiser', to='system.advertiser')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MtaResult_Campaign', to='system.campaign')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MtaResult_chanel', to='system.channel')),
                ('conversion_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MtaResult_conversionType', to='mta.conversiontype')),
            ],
            options={
                'verbose_name_plural': 'MTA Result',
            },
        ),
    ]
